openapi: 3.0.0
info:
  title: prodb API
  description: nil
  version: 0.1.9
  contact:
    email: jokanolaadedipupo@gmail.com
    url: https://github.com/
# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing
servers:
  - url: "{protocol}://localhost:4000/api/v1/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
            
components:
  securitySchemas:
    cookieAuth:
      type: apikey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer         

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
           description: Bad request
        '500':
           description: Internal server error
